ARG BASE_IMAGE=base

FROM ${BASE_IMAGE} AS base
WORKDIR /app
WORKDIR /app/volo/abp/templates/ms/shared/saasLMS.DbMigrator
RUN dotnet publish -c Release -o bin/Release/publish

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS publish
WORKDIR /app
EXPOSE 80
ENV ASPNETCORE_URLS=http://+:80
COPY --from=base /app/volo/abp/templates/ms/shared/saasLMS.DbMigrator/bin/Release/publish .
ENTRYPOINT ["dotnet", "saasLMS.DbMigrator.dll"]
