// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Volo.Abp.EntityFrameworkCore;
using saasLMS.ReportingService.EntityFrameworkCore;

#nullable disable

namespace saasLMS.ReportingService.Migrations
{
    [DbContext(typeof(ReportingServiceDbContext))]
    [Migration("20260413090000_Remove_TenantSummary_TotalInstructors")]
    partial class RemoveTenantSummaryTotalInstructors : Migration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("_Abp_DatabaseProvider", EfCoreDatabaseProvider.SqlServer)
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("saasLMS.ReportingService.ReadModels.ClassProgressView", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ActiveEnrollmentCount")
                        .HasColumnType("int");

                    b.Property<int>("Bucket_0_25")
                        .HasColumnType("int");

                    b.Property<int>("Bucket_100")
                        .HasColumnType("int");

                    b.Property<int>("Bucket_26_50")
                        .HasColumnType("int");

                    b.Property<int>("Bucket_51_75")
                        .HasColumnType("int");

                    b.Property<int>("Bucket_76_99")
                        .HasColumnType("int");

                    b.Property<int>("CompletedCount")
                        .HasColumnType("int");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("InProgressCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastRecalculatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TotalStudents")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "CourseId")
                        .IsUnique();

                    b.ToTable("ClassProgressViews", (string)null);
                });

            modelBuilder.Entity("saasLMS.ReportingService.ReadModels.CourseOutcomeReportView", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AssignmentGradedCount")
                        .HasColumnType("int");

                    b.Property<decimal>("AssignmentScoreSum")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AvgAssignmentScore")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AvgQuizScore")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CompletionRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("FinalScoreAvg")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("FinalScoreCount")
                        .HasColumnType("int");

                    b.Property<decimal>("FinalScoreSum")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PassRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("QuizCompletedCount")
                        .HasColumnType("int");

                    b.Property<decimal>("QuizScoreSum")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ScoreDistributionJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TotalAssignmentsCount")
                        .HasColumnType("int");

                    b.Property<int>("TotalLessonsCount")
                        .HasColumnType("int");

                    b.Property<int>("TotalQuizzesCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "CourseId")
                        .IsUnique();

                    b.ToTable("CourseOutcomeReportViews", (string)null);
                });

            modelBuilder.Entity("saasLMS.ReportingService.ReadModels.StudentCourseProgressView", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AssignmentCompletionPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("AssignmentGradedCount")
                        .HasColumnType("int");

                    b.Property<decimal>("AssignmentScoreSum")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AvgAssignmentScore")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AvgQuizScore")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CompletedLessonsCount")
                        .HasColumnType("int");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActiveEnrollment")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastAccessedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastAccessedLessonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("LessonCompletionPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("OverallProgress")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("QuizCompletedCount")
                        .HasColumnType("int");

                    b.Property<decimal>("QuizCompletionPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("QuizScoreSum")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TotalAssignmentsCount")
                        .HasColumnType("int");

                    b.Property<int>("TotalLessonsCount")
                        .HasColumnType("int");

                    b.Property<int>("TotalQuizzesCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "CourseId", "StudentId")
                        .IsUnique();

                    b.ToTable("StudentCourseProgressViews", (string)null);
                });

            modelBuilder.Entity("saasLMS.ReportingService.ReadModels.TenantSummaryReportView", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ActiveCourses")
                        .HasColumnType("int");

                    b.Property<int>("ActiveStudents")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TotalCourses")
                        .HasColumnType("int");

                    b.Property<int>("TotalStudents")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.ToTable("TenantSummaryReportViews", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
