// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using saasLMS.CourseCatalogService.Courses;
using saasLMS.CourseCatalogService.Courses.Dtos.Outputs;
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace saasLMS.CourseCatalogService.Courses.Dtos.Outputs;

public class CourseEligibilityDto
{
    public Guid CourseId { get; set; }

    public Guid TenantId { get; set; }

    public CourseStatus Status { get; set; }

    public bool IsHidden { get; set; }
}
