// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using saasLMS.AssessmentService.Submissions;
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace saasLMS.AssessmentService.Submissions;

public class GradeSubmissionDto
{
    public Decimal Score { get; set; }
}
