// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
#nullable enable
using saasLMS.AssessmentService.Submissions;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Content;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace saasLMS.AssessmentService.Submissions;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(ISubmissionAppService), typeof(SubmissionClientProxy))]
public partial class SubmissionClientProxy : ClientProxyBase<ISubmissionAppService>, ISubmissionAppService
{
    public virtual async Task<SubmissionDto> SubmitAsync(SubmitSubmissionDto input)
    {
        return await RequestAsync<SubmissionDto>(nameof(SubmitAsync), new ClientProxyRequestTypeValue
        {
            { typeof(SubmitSubmissionDto), input }
        });
    }

    public virtual async Task<SubmissionDto> GradeAsync(Guid submissionId, GradeSubmissionDto input)
    {
        return await RequestAsync<SubmissionDto>(nameof(GradeAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), submissionId },
            { typeof(GradeSubmissionDto), input }
        });
    }

    public virtual async Task<SubmissionDto> GetAsync(Guid id)
    {
        return await RequestAsync<SubmissionDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<List<SubmissionListItemDto>> GetListByAssignmentAsync(Guid assignmentId)
    {
        return await RequestAsync<List<SubmissionListItemDto>>(nameof(GetListByAssignmentAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), assignmentId }
        });
    }

    public virtual async Task<SubmissionDto?> GetMySubmissionByAssignmentAsync(Guid assignmentId)
    {
        return await RequestAsync<SubmissionDto?>(nameof(GetMySubmissionByAssignmentAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), assignmentId }
        });
    }

    /// <summary>
    /// UploadSubmissionFileAsync is handled via a dedicated multipart/form-data controller (SubmissionFileController).
    /// Use IHttpClientFactory to call POST /api/assessment/submission/upload-submission-file directly.
    /// </summary>
    public Task<SubmissionDto> UploadSubmissionFileAsync(UploadSubmissionFileInput input, IRemoteStreamContent file)
    {
        throw new NotImplementedException(
            "UploadSubmissionFileAsync is handled by SubmissionFileController (multipart/form-data). " +
            "Use IHttpClientFactory to POST to /api/assessment/submission/upload-submission-file.");
    }

    /// <summary>
    /// DownloadSubmissionFileAsync is handled via a dedicated streaming controller endpoint.
    /// Use IHttpClientFactory to call the download endpoint directly.
    /// </summary>
    public Task<IRemoteStreamContent> DownloadSubmissionFileAsync(DownloadSubmissionFileInput input)
    {
        throw new NotImplementedException(
            "DownloadSubmissionFileAsync requires direct HTTP streaming. " +
            "Use IHttpClientFactory to call the download endpoint directly.");
    }

    /// <summary>
    /// DownloadMySubmissionFileAsync is handled via a dedicated streaming controller endpoint.
    /// Use IHttpClientFactory to call the download endpoint directly.
    /// </summary>
    public Task<IRemoteStreamContent> DownloadMySubmissionFileAsync(DownloadSubmissionFileInput input)
    {
        throw new NotImplementedException(
            "DownloadMySubmissionFileAsync requires direct HTTP streaming. " +
            "Use IHttpClientFactory to call the download endpoint directly.");
    }
}
