// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using saasLMS.AssessmentService.Shared;
using saasLMS.AssessmentService.Submissions;
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace saasLMS.AssessmentService.Submissions;

public class SubmissionListItemDto
{
    public Guid Id { get; set; }

    public Guid AssignmentId { get; set; }

    public Guid StudentId { get; set; }

    public ContentType ContentType { get; set; }

    public string FileName { get; set; }

    public SubmissionStatus Status { get; set; }

    public Decimal? Score { get; set; }

    public DateTime SubmittedAt { get; set; }

    public DateTime? GradedAt { get; set; }
}
