// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using Microsoft.AspNetCore.Http;
using saasLMS.AssessmentService.Submissions;
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace saasLMS.AssessmentService.Submissions;

public class UploadSubmissionFileRequest
{
    public Guid SubmissionId { get; set; }

    public IFormFile File { get; set; }
}
