// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using saasLMS.AssessmentService.Assignments;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace saasLMS.AssessmentService.Assignments;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IAssignmentAppService), typeof(AssignmentClientProxy))]
public partial class AssignmentClientProxy : ClientProxyBase<IAssignmentAppService>, IAssignmentAppService
{
    public virtual async Task<AssignmentDto> CreateAsync(CreateAssignmentDto input)
    {
        return await RequestAsync<AssignmentDto>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(CreateAssignmentDto), input }
        });
    }

    public virtual async Task<AssignmentDto> UpdateAsync(Guid id, UpdateAssignmentDto input)
    {
        return await RequestAsync<AssignmentDto>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(UpdateAssignmentDto), input }
        });
    }

    public virtual async Task PublishAsync(Guid id)
    {
        await RequestAsync(nameof(PublishAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task CloseAsync(Guid id)
    {
        await RequestAsync(nameof(CloseAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<AssignmentDto> GetAsync(Guid id)
    {
        return await RequestAsync<AssignmentDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<AssignmentDto> GetStudentAsync(Guid id)
    {
        return await RequestAsync<AssignmentDto>(nameof(GetStudentAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<List<AssignmentListItemDto>> GetListByCourseAsync(Guid courseId)
    {
        return await RequestAsync<List<AssignmentListItemDto>>(nameof(GetListByCourseAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), courseId }
        });
    }

    public virtual async Task<List<AssignmentListItemDto>> GetListByLessonAsync(Guid lessonId)
    {
        return await RequestAsync<List<AssignmentListItemDto>>(nameof(GetListByLessonAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), lessonId }
        });
    }

    public virtual async Task<List<AssignmentListItemDto>> GetListByCourseStudentAsync(Guid courseId)
    {
        return await RequestAsync<List<AssignmentListItemDto>>(nameof(GetListByCourseStudentAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), courseId }
        });
    }

    public virtual async Task<List<AssignmentListItemDto>> GetListByLessonStudentAsync(Guid lessonId)
    {
        return await RequestAsync<List<AssignmentListItemDto>>(nameof(GetListByLessonStudentAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), lessonId }
        });
    }
}