// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using saasLMS.AssessmentService.Assignments;
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace saasLMS.AssessmentService.Assignments;

public class UpdateAssignmentDto
{
    public string Title { get; set; }

    public string Description { get; set; }

    public DateTime? Deadline { get; set; }

    public Decimal MaxScore { get; set; }
}
