// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using saasLMS.LearningProgressService.CourseProgresses.Dtos.Outputs;
using saasLMS.LearningProgressService.LessonProgresses;
using saasLMS.LearningProgressService.LessonProgresses.Dtos.Inputs;
using saasLMS.LearningProgressService.LessonProgresses.Dtos.Outputs;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace saasLMS.LearningProgressService;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(ILearningProgressAppService), typeof(LearningProgressClientProxy))]
public partial class LearningProgressClientProxy : ClientProxyBase<ILearningProgressAppService>, ILearningProgressAppService
{
    public virtual async Task<LessonProgressDto> StartLessonAsync(StartLessonInput input)
    {
        return await RequestAsync<LessonProgressDto>(nameof(StartLessonAsync), new ClientProxyRequestTypeValue
        {
            { typeof(StartLessonInput), input }
        });
    }

    public virtual async Task<LessonProgressDto> CompleteLessonAsync(CompleteLessonInput input)
    {
        return await RequestAsync<LessonProgressDto>(nameof(CompleteLessonAsync), new ClientProxyRequestTypeValue
        {
            { typeof(CompleteLessonInput), input }
        });
    }

    public virtual async Task<List<LessonProgressDto>> GetMyProgressAsync(Guid courseId)
    {
        return await RequestAsync<List<LessonProgressDto>>(nameof(GetMyProgressAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), courseId }
        });
    }

    public virtual async Task<CourseProgressDto> GetMyCourseProgressAsync(Guid courseId)
    {
        return await RequestAsync<CourseProgressDto>(nameof(GetMyCourseProgressAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), courseId }
        });
    }

    public virtual async Task<ResumeResultDto> GetResumePositionAsync(Guid courseId)
    {
        return await RequestAsync<ResumeResultDto>(nameof(GetResumePositionAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), courseId }
        });
    }
}
