// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using saasLMS.ReportingService.Reports;
using saasLMS.ReportingService.Reports.Dtos.Outputs;
using System;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace saasLMS.ReportingService.Reports;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IReportingAppService), typeof(ReportingClientProxy))]
public partial class ReportingClientProxy : ClientProxyBase<IReportingAppService>, IReportingAppService
{
    public virtual async Task<StudentCourseProgressViewDto?> GetStudentCourseProgressAsync(Guid courseId)
    {
        return await RequestAsync<StudentCourseProgressViewDto?>(nameof(GetStudentCourseProgressAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), courseId }
        });
    }

    public virtual async Task<ClassProgressViewDto?> GetClassProgressAsync(Guid courseId)
    {
        return await RequestAsync<ClassProgressViewDto?>(nameof(GetClassProgressAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), courseId }
        });
    }

    public virtual async Task<CourseOutcomeReportViewDto?> GetCourseOutcomeReportAsync(Guid courseId)
    {
        return await RequestAsync<CourseOutcomeReportViewDto?>(nameof(GetCourseOutcomeReportAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), courseId }
        });
    }

    public virtual async Task<TenantSummaryReportViewDto?> GetTenantSummaryAsync()
    {
        return await RequestAsync<TenantSummaryReportViewDto?>(nameof(GetTenantSummaryAsync));
    }
}
