version: '3.8'

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management-alpine
    networks:
      - saaslms-network
      
  redis:
    container_name: redis
    image: redis:alpine
    networks:
      - saaslms-network
      
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.3
    # volumes:
    #   - esdata:/usr/share/elasticsearch/data
    networks:
      - saaslms-network
      
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.5.3
    depends_on:
      - elasticsearch
    networks:
      - saaslms-network
    
  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/azure-sql-edge
    volumes:
      - sqldata:/var/opt/mssql
    networks:
      - saaslms-network
 
  grafana:
    container_name: grafana
    image: grafana/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
      - GF_SERVER_DOMAIN=grafana.trananhminh.uk
      - GF_SERVER_ROOT_URL=https://grafana.trananhminh.uk/
      - GF_SERVER_SERVE_FROM_SUB_PATH=false
    volumes:
      - ../grafana/storage:/var/lib/grafana
      - ../grafana/provisioning:/etc/grafana/provisioning
      - ../grafana/dashboards:/etc/grafana/dashboards
    networks:
      - saaslms-network

  loki:
    container_name: loki
    image: grafana/loki:3.1.1
    command:
      - -config.file=/etc/loki/config.yml
    volumes:
      - ../loki/config.yml:/etc/loki/config.yml
      - ../loki/storage:/loki
    networks:
      - saaslms-network

  alertmanager:
    container_name: alertmanager
    image: prom/alertmanager:v0.28.1
    command:
      - --config.file=/etc/alertmanager/alertmanager.yml
      - --storage.path=/alertmanager
    volumes:
      - ../alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - ../alertmanager/storage:/alertmanager
    networks:
      - saaslms-network
      
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=15d
    volumes:
      - ../prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ../prometheus/rules:/etc/prometheus/rules
      - ../prometheus/storage:/prometheus
    networks:
      - saaslms-network
      
volumes:
  esdata:
  sqldata:
networks:
  saaslms-network:
    external: true
