// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using saasLMS.AssessmentService.Shared;
using System;

// ReSharper disable once CheckNamespace
namespace saasLMS.AssessmentService.Quizzes;

public class CreateQuizFromCsvDto
{
    public Guid CourseId { get; set; }
    public Guid LessonId { get; set; }
    public string Title { get; set; } = string.Empty;
    public int? TimeLimitMinutes { get; set; }
    public decimal MaxScore { get; set; }
    public AttemptPolicy AttemptPolicy { get; set; }
}
