// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using saasLMS.AssessmentService.Quizzes;
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace saasLMS.AssessmentService.Quizzes;

public class QuizFormQuestionDto
{
    public Guid Id { get; set; }

    public int Index { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public bool IsRequired { get; set; }

    public string QuestionType { get; set; }

    public QuizFormChoiceDto[] Choices { get; set; }
}
