// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using saasLMS.AssessmentService.Quizzes;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Content;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace saasLMS.AssessmentService.Quizzes;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IQuizAppService), typeof(QuizClientProxy))]
public partial class QuizClientProxy : ClientProxyBase<IQuizAppService>, IQuizAppService
{
    public virtual async Task<QuizDto> CreateAsync(CreateQuizDto input)
    {
        return await RequestAsync<QuizDto>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(CreateQuizDto), input }
        });
    }

    public virtual async Task<QuizDto> UpdateAsync(Guid id, UpdateQuizDto input)
    {
        return await RequestAsync<QuizDto>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id },
            { typeof(UpdateQuizDto), input }
        });
    }

    public virtual async Task PublishAsync(Guid id)
    {
        await RequestAsync(nameof(PublishAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task CloseAsync(Guid id)
    {
        await RequestAsync(nameof(CloseAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<QuizDto> GetAsync(Guid id)
    {
        return await RequestAsync<QuizDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<QuizDto> GetStudentAsync(Guid id)
    {
        return await RequestAsync<QuizDto>(nameof(GetStudentAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<List<QuizListItemDto>> GetListByCourseAsync(Guid courseId)
    {
        return await RequestAsync<List<QuizListItemDto>>(nameof(GetListByCourseAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), courseId }
        });
    }

    public virtual async Task<List<QuizListItemDto>> GetListByLessonAsync(Guid lessonId)
    {
        return await RequestAsync<List<QuizListItemDto>>(nameof(GetListByLessonAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), lessonId }
        });
    }

    public virtual async Task<List<QuizListItemDto>> GetListByCourseStudentAsync(Guid lessonId)
    {
        return await RequestAsync<List<QuizListItemDto>>(nameof(GetListByCourseStudentAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), lessonId }
        });
    }

    public virtual async Task<List<QuizListItemDto>> GetListByLessonStudentAsync(Guid lessonId)
    {
        return await RequestAsync<List<QuizListItemDto>>(nameof(GetListByLessonStudentAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), lessonId }
        });
    }

    /// <summary>
    /// CreateFromCsvAsync is handled via a dedicated multipart/form-data controller (QuizCsvController).
    /// Use IHttpClientFactory to call POST /api/assessment/quiz/upload-csv directly.
    /// </summary>
    public Task<QuizDto> CreateFromCsvAsync(CreateQuizFromCsvDto input, IRemoteStreamContent file)
    {
        throw new NotImplementedException(
            "CreateFromCsvAsync is handled by QuizCsvController (multipart/form-data). " +
            "Use IHttpClientFactory to POST to /api/assessment/quiz/upload-csv.");
    }

    public virtual async Task<QuizFormSchemaDto> GetFormSchemaAsync(Guid quizId)
    {
        return await RequestAsync<QuizFormSchemaDto>(nameof(GetFormSchemaAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), quizId }
        });
    }
}
