// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using saasLMS.AssessmentService.Quizzes;
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace saasLMS.AssessmentService.Quizzes;

public class QuizFormChoiceDto
{
    public Guid Id { get; set; }

    public int Index { get; set; }

    public string Value { get; set; }
}
