// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using saasLMS.AssessmentService.Quizzes;
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace saasLMS.AssessmentService.Quizzes;

public class QuizFormSchemaDto
{
    public Guid FormId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public QuizFormQuestionDto[] Questions { get; set; }
}
