// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using saasLMS.AssessmentService.Quizzes;
using saasLMS.AssessmentService.Shared;
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace saasLMS.AssessmentService.Quizzes;

public class QuizDto
{
    public Guid Id { get; set; }

    public Guid CourseId { get; set; }

    public Guid LessonId { get; set; }

    public string Title { get; set; }

    public int? TimeLimitMinutes { get; set; }

    public Decimal MaxScore { get; set; }

    public AttemptPolicy AttemptPolicy { get; set; }

    public string QuestionsJson { get; set; }

    public QuizStatus Status { get; set; }

    public DateTime? PublishedAt { get; set; }

    public DateTime? ClosedAt { get; set; }
}
