// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using saasLMS.AssessmentService.Quizzes;
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace saasLMS.AssessmentService.Quizzes;

public enum QuizStatus
{
    Draft = 0,
    Published = 1,
    Closed = 2
}
