// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using saasLMS.AssessmentService.Quizzes;
using saasLMS.AssessmentService.Shared;
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace saasLMS.AssessmentService.Quizzes;

public class UpdateQuizDto
{
    public string Title { get; set; }

    public int? TimeLimitMinutes { get; set; }

    public Decimal MaxScore { get; set; }

    public AttemptPolicy AttemptPolicy { get; set; }

    public string QuestionsJson { get; set; }
}
