// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using Microsoft.AspNetCore.Http;
using saasLMS.AssessmentService.Quizzes;
using saasLMS.AssessmentService.Shared;
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace saasLMS.AssessmentService.Quizzes;

public class UploadQuizCsvRequest
{
    public Guid CourseId { get; set; }

    public Guid LessonId { get; set; }

    public string Title { get; set; }

    public int? TimeLimitMinutes { get; set; }

    public Decimal MaxScore { get; set; }

    public AttemptPolicy AttemptPolicy { get; set; }

    public IFormFile File { get; set; }
}
