// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using saasLMS.CourseCatalogService.Courses.Dtos.Inputs;
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace saasLMS.CourseCatalogService.Courses.Dtos.Inputs;

public class CreateCourseInput
{
    public string Title { get; set; }

    public string Description { get; set; }

    public Guid InstructorId { get; set; }
}
