// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using saasLMS.EnrollmentService.Enrollments;
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace saasLMS.EnrollmentService.Enrollments;

public enum EnrollmentStatus
{
    Active = 0,
    Completed = 1,
    Cancelled = 2
}
