// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using saasLMS.CourseCatalogService.Chapters.Dtos.Inputs;
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace saasLMS.CourseCatalogService.Chapters.Dtos.Inputs;

public class CreateChapterInput
{
    public Guid CourseId { get; set; }

    public string Title { get; set; }
}
