// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using saasLMS.EnrollmentService.Enrollments;
using saasLMS.EnrollmentService.Enrollments.Dtos.Inputs;
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace saasLMS.EnrollmentService.Enrollments.Dtos.Inputs;

public class GetMyEnrollmentsInput
{
    public EnrollmentStatus? Status { get; set; }
}
