---
- name: Initialize Docker Swarm manager
  hosts: manager
  become: true
  roles:
    - common
    - docker
    - swarm-manager

- name: Join worker nodes to Docker Swarm
  hosts: workers
  become: true
  roles:
    - common
    - docker
    - swarm-worker

- name: Deploy monitoring exporters stack to Swarm manager
  hosts: manager
  become: true
  roles:
    - monitoring-stack
