all:
  children:
    manager:
      hosts:
        manager1:
          ansible_host: 47.130.61.0
          manager_private_ip: 10.0.1.249

    workers:
      hosts: {}

    infra:
      hosts:
        infra1:
          ansible_host: 54.255.164.115
          infra_private_ip: 10.0.1.138

  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/saaslms.pem
    ansible_python_interpreter: /usr/bin/python3
