config:
  selfUrl: # https://gateway-public.saaslms.dev
  corsOrigins: # https://saaslms-st-gateway-web,https://saaslms-st-gateway-public-web
  authServer:
    authority: # http://saaslms-st-authserver
    requireHttpsMetadata: # "false"
    metadataAddress: # https://authserver.saaslms.dev/.well-known/openid-configuration
    swaggerClientId: # WebGateway_Swagger
  dotnetEnv: Staging 
  redisHost: #
  rabbitmqHost: #
  elasticsearchUrl: #
  AbpLicenseCode: #

reRoutes:
  accountService:
    url: http://saaslms-st-authserver
  saasService:
    url: http://saas-st-administration
  administrationService:
    url: http://saaslms-st-administration
  productService:
    url: http://saaslms-st-product

ingress:
  host: gateway-public.saaslms.dev
  tlsSecret: saaslms-tls

image:
  repository: mycompanyname/saaslms-gateway-web-public
  tag: latest
  pullPolicy: IfNotPresent

env: {}
    