// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using saasLMS.CourseCatalogService.Chapters.Dtos.Inputs;
using saasLMS.CourseCatalogService.Chapters.Dtos.Outputs;
using saasLMS.CourseCatalogService.Courses;
using saasLMS.CourseCatalogService.Courses.Dtos.Inputs;
using saasLMS.CourseCatalogService.Courses.Dtos.Outputs;
using saasLMS.CourseCatalogService.Lessons.Dtos.Inputs;
using saasLMS.CourseCatalogService.Lessons.Dtos.Outputs;
using saasLMS.CourseCatalogService.Materials.Dtos.Inputs;
using saasLMS.CourseCatalogService.Materials.Dtos.Outputs;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Content;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace saasLMS.CourseCatalogService;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(ICourseCatalogAppService), typeof(CourseCatalogClientProxy))]
public partial class CourseCatalogClientProxy : ClientProxyBase<ICourseCatalogAppService>, ICourseCatalogAppService
{
    public virtual async Task<CourseDto> CreateCourseAsync(CreateCourseInput input)
    {
        return await RequestAsync<CourseDto>(nameof(CreateCourseAsync), new ClientProxyRequestTypeValue
        {
            { typeof(CreateCourseInput), input }
        });
    }

    public virtual async Task<CourseDto> RenameCourseAsync(RenameCourseInput input)
    {
        return await RequestAsync<CourseDto>(nameof(RenameCourseAsync), new ClientProxyRequestTypeValue
        {
            { typeof(RenameCourseInput), input }
        });
    }

    public virtual async Task<CourseDto> UpdateCourseAsync(UpdateCourseInput input)
    {
        return await RequestAsync<CourseDto>(nameof(UpdateCourseAsync), new ClientProxyRequestTypeValue
        {
            { typeof(UpdateCourseInput), input }
        });
    }

    public virtual async Task PublishCourseAsync(PublishCourseInput input)
    {
        await RequestAsync(nameof(PublishCourseAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PublishCourseInput), input }
        });
    }

    public virtual async Task HideCourseAsync(HideCourseInput input)
    {
        await RequestAsync(nameof(HideCourseAsync), new ClientProxyRequestTypeValue
        {
            { typeof(HideCourseInput), input }
        });
    }

    public virtual async Task ReopenCourseAsync(ReopenCourseInput input)
    {
        await RequestAsync(nameof(ReopenCourseAsync), new ClientProxyRequestTypeValue
        {
            { typeof(ReopenCourseInput), input }
        });
    }

    public virtual async Task<CourseDto> GetCourseAsync(Guid id)
    {
        return await RequestAsync<CourseDto>(nameof(GetCourseAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<CourseDto> GetCourseStudentAsync(Guid id)
    {
        return await RequestAsync<CourseDto>(nameof(GetCourseStudentAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<CourseOwnerDto> GetOwnerAsync(Guid id)
    {
        return await RequestAsync<CourseOwnerDto>(nameof(GetOwnerAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<CourseEligibilityDto> GetEnrollmentEligibilityAsync(Guid courseId, Guid tenantId)
    {
        return await RequestAsync<CourseEligibilityDto>(nameof(GetEnrollmentEligibilityAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), courseId },
            { typeof(Guid), tenantId }
        });
    }

    public virtual async Task<CourseDetailDto> GetCourseDetailAsync(Guid id)
    {
        return await RequestAsync<CourseDetailDto>(nameof(GetCourseDetailAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<CourseDetailDto> GetCourseDetailStudentAsync(Guid id)
    {
        return await RequestAsync<CourseDetailDto>(nameof(GetCourseDetailStudentAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<List<CourseListItemDto>> GetPublishedCoursesAsync()
    {
        return await RequestAsync<List<CourseListItemDto>>(nameof(GetPublishedCoursesAsync));
    }

    public virtual async Task<List<CourseListItemDto>> GetCoursesByInstructorAsync(Guid instructorId)
    {
        return await RequestAsync<List<CourseListItemDto>>(nameof(GetCoursesByInstructorAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), instructorId }
        });
    }

    public virtual async Task<List<CourseListItemDto>> GetPublishedCoursesByInstructorAsync(Guid instructorId)
    {
        return await RequestAsync<List<CourseListItemDto>>(nameof(GetPublishedCoursesByInstructorAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), instructorId }
        });
    }

    public virtual async Task<List<CourseListItemDto>> GetCoursesByTenantAsync()
    {
        return await RequestAsync<List<CourseListItemDto>>(nameof(GetCoursesByTenantAsync));
    }

    public virtual async Task<List<CourseListItemDto>> GetPublishedCoursesByTenantAsync()
    {
        return await RequestAsync<List<CourseListItemDto>>(nameof(GetPublishedCoursesByTenantAsync));
    }

    public virtual async Task<ChapterDto> CreateChapterAsync(CreateChapterInput input)
    {
        return await RequestAsync<ChapterDto>(nameof(CreateChapterAsync), new ClientProxyRequestTypeValue
        {
            { typeof(CreateChapterInput), input }
        });
    }

    public virtual async Task<ChapterDto> RenameChapterAsync(RenameChapterInput input)
    {
        return await RequestAsync<ChapterDto>(nameof(RenameChapterAsync), new ClientProxyRequestTypeValue
        {
            { typeof(RenameChapterInput), input }
        });
    }

    public virtual async Task RemoveChapterAsync(RemoveChapterInput input)
    {
        await RequestAsync(nameof(RemoveChapterAsync), new ClientProxyRequestTypeValue
        {
            { typeof(RemoveChapterInput), input }
        });
    }

    public virtual async Task ReorderChaptersAsync(ReorderChaptersInput input)
    {
        await RequestAsync(nameof(ReorderChaptersAsync), new ClientProxyRequestTypeValue
        {
            { typeof(ReorderChaptersInput), input }
        });
    }

    public virtual async Task<ChapterDto> GetChapterAsync(Guid courseId, Guid chapterId)
    {
        return await RequestAsync<ChapterDto>(nameof(GetChapterAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), courseId },
            { typeof(Guid), chapterId }
        });
    }

    public virtual async Task<List<ChapterDto>> GetChaptersByCourseAsync(Guid courseId)
    {
        return await RequestAsync<List<ChapterDto>>(nameof(GetChaptersByCourseAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), courseId }
        });
    }

    public virtual async Task<List<ChapterDto>> GetChaptersByCourseStudentAsync(Guid courseId)
    {
        return await RequestAsync<List<ChapterDto>>(nameof(GetChaptersByCourseStudentAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), courseId }
        });
    }

    public virtual async Task<ChapterDto> GetChapterStudentAsync(Guid courseId, Guid chapterId)
    {
        return await RequestAsync<ChapterDto>(nameof(GetChapterStudentAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), courseId },
            { typeof(Guid), chapterId }
        });
    }

    public virtual async Task<LessonDto> CreateLessonAsync(CreateLessonInput input)
    {
        return await RequestAsync<LessonDto>(nameof(CreateLessonAsync), new ClientProxyRequestTypeValue
        {
            { typeof(CreateLessonInput), input }
        });
    }

    public virtual async Task<LessonDto> RenameLessonAsync(RenameLessonInput input)
    {
        return await RequestAsync<LessonDto>(nameof(RenameLessonAsync), new ClientProxyRequestTypeValue
        {
            { typeof(RenameLessonInput), input }
        });
    }

    public virtual async Task<LessonDto> UpdateLessonAsync(UpdateLessonInput input)
    {
        return await RequestAsync<LessonDto>(nameof(UpdateLessonAsync), new ClientProxyRequestTypeValue
        {
            { typeof(UpdateLessonInput), input }
        });
    }

    public virtual async Task RemoveLessonAsync(RemoveLessonInput input)
    {
        await RequestAsync(nameof(RemoveLessonAsync), new ClientProxyRequestTypeValue
        {
            { typeof(RemoveLessonInput), input }
        });
    }

    public virtual async Task<List<LessonDto>> GetLessonsByChapterAsync(Guid courseId, Guid chapterId)
    {
        return await RequestAsync<List<LessonDto>>(nameof(GetLessonsByChapterAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), courseId },
            { typeof(Guid), chapterId }
        });
    }

    public virtual async Task<LessonDto> GetLessonAsync(Guid courseId, Guid chapterId, Guid lessonId)
    {
        return await RequestAsync<LessonDto>(nameof(GetLessonAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), courseId },
            { typeof(Guid), chapterId },
            { typeof(Guid), lessonId }
        });
    }

    public virtual async Task<List<LessonDto>> GetLessonsByChapterStudentAsync(Guid courseId, Guid chapterId)
    {
        return await RequestAsync<List<LessonDto>>(nameof(GetLessonsByChapterStudentAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), courseId },
            { typeof(Guid), chapterId }
        });
    }

    public virtual async Task<LessonDto> GetLessonStudentAsync(Guid courseId, Guid chapterId, Guid lessonId)
    {
        return await RequestAsync<LessonDto>(nameof(GetLessonStudentAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), courseId },
            { typeof(Guid), chapterId },
            { typeof(Guid), lessonId }
        });
    }

    public virtual async Task<MaterialDto> CreateFileMaterialAsync(CreateFileMaterialInput input)
    {
        return await RequestAsync<MaterialDto>(nameof(CreateFileMaterialAsync), new ClientProxyRequestTypeValue
        {
            { typeof(CreateFileMaterialInput), input }
        });
    }

    public virtual async Task<MaterialDto> CreateVideoLinkMaterialAsync(CreateVideoLinkMaterialInput input)
    {
        return await RequestAsync<MaterialDto>(nameof(CreateVideoLinkMaterialAsync), new ClientProxyRequestTypeValue
        {
            { typeof(CreateVideoLinkMaterialInput), input }
        });
    }

    public virtual async Task<MaterialDto> CreateTextMaterialAsync(CreateTextMaterialInput input)
    {
        return await RequestAsync<MaterialDto>(nameof(CreateTextMaterialAsync), new ClientProxyRequestTypeValue
        {
            { typeof(CreateTextMaterialInput), input }
        });
    }

    public virtual async Task<MaterialDto> RenameMaterialAsync(RenameMaterialInput input)
    {
        return await RequestAsync<MaterialDto>(nameof(RenameMaterialAsync), new ClientProxyRequestTypeValue
        {
            { typeof(RenameMaterialInput), input }
        });
    }

    public virtual async Task<MaterialDto> UpdateFileMaterialAsync(UpdateFileMaterialInput input)
    {
        return await RequestAsync<MaterialDto>(nameof(UpdateFileMaterialAsync), new ClientProxyRequestTypeValue
        {
            { typeof(UpdateFileMaterialInput), input }
        });
    }

    public virtual async Task<MaterialDto> UpdateVideoLinkMaterialAsync(UpdateVideoLinkMaterialInput input)
    {
        return await RequestAsync<MaterialDto>(nameof(UpdateVideoLinkMaterialAsync), new ClientProxyRequestTypeValue
        {
            { typeof(UpdateVideoLinkMaterialInput), input }
        });
    }

    public virtual async Task<MaterialDto> UpdateTextMaterialAsync(UpdateTextMaterialInput input)
    {
        return await RequestAsync<MaterialDto>(nameof(UpdateTextMaterialAsync), new ClientProxyRequestTypeValue
        {
            { typeof(UpdateTextMaterialInput), input }
        });
    }

    public virtual async Task HideMaterialAsync(HideMaterialInput input)
    {
        await RequestAsync(nameof(HideMaterialAsync), new ClientProxyRequestTypeValue
        {
            { typeof(HideMaterialInput), input }
        });
    }

    public virtual async Task ActivateMaterialAsync(ActivateMaterialInput input)
    {
        await RequestAsync(nameof(ActivateMaterialAsync), new ClientProxyRequestTypeValue
        {
            { typeof(ActivateMaterialInput), input }
        });
    }

    public virtual async Task RemoveMaterialAsync(RemoveMaterialInput input)
    {
        await RequestAsync(nameof(RemoveMaterialAsync), new ClientProxyRequestTypeValue
        {
            { typeof(RemoveMaterialInput), input }
        });
    }

    public virtual async Task<List<MaterialDto>> GetMaterialsByLessonAsync(Guid courseId, Guid chapterId, Guid lessonId)
    {
        return await RequestAsync<List<MaterialDto>>(nameof(GetMaterialsByLessonAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), courseId },
            { typeof(Guid), chapterId },
            { typeof(Guid), lessonId }
        });
    }

    public virtual async Task<MaterialDto> GetMaterialAsync(Guid courseId, Guid chapterId, Guid lessonId, Guid materialId)
    {
        return await RequestAsync<MaterialDto>(nameof(GetMaterialAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), courseId },
            { typeof(Guid), chapterId },
            { typeof(Guid), lessonId },
            { typeof(Guid), materialId }
        });
    }

    public virtual async Task<List<MaterialDto>> GetMaterialsByLessonStudentAsync(Guid courseId, Guid chapterId, Guid lessonId)
    {
        return await RequestAsync<List<MaterialDto>>(nameof(GetMaterialsByLessonStudentAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), courseId },
            { typeof(Guid), chapterId },
            { typeof(Guid), lessonId }
        });
    }

    public virtual async Task<MaterialDto> GetMaterialStudentAsync(Guid courseId, Guid chapterId, Guid lessonId, Guid materialId)
    {
        return await RequestAsync<MaterialDto>(nameof(GetMaterialStudentAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), courseId },
            { typeof(Guid), chapterId },
            { typeof(Guid), lessonId },
            { typeof(Guid), materialId }
        });
    }

    public virtual async Task<IRemoteStreamContent> DownloadMaterialFileAsync(DownloadMaterialFileInput input)
    {
        return await RequestAsync<IRemoteStreamContent>(nameof(DownloadMaterialFileAsync), new ClientProxyRequestTypeValue
        {
            { typeof(DownloadMaterialFileInput), input }
        });
    }

    public virtual async Task<IRemoteStreamContent> DownloadMaterialFileStudentAsync(DownloadMaterialFileInput input)
    {
        return await RequestAsync<IRemoteStreamContent>(nameof(DownloadMaterialFileStudentAsync), new ClientProxyRequestTypeValue
        {
            { typeof(DownloadMaterialFileInput), input }
        });
    }
}
