// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using saasLMS.CourseCatalogService.Courses;
using saasLMS.CourseCatalogService.Materials.Dtos.Outputs;
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace saasLMS.CourseCatalogService.Materials.Dtos.Outputs;

public class MaterialDto
{
    public Guid Id { get; set; }

    public Guid CourseId { get; set; }

    public Guid ChapterId { get; set; }

    public Guid LessonId { get; set; }

    public string Title { get; set; }

    public MaterialType Type { get; set; }

    public MaterialStatus Status { get; set; }

    public int SortOrder { get; set; }

    public string StorageKey { get; set; }

    public string FileName { get; set; }

    public string MimeType { get; set; }

    public long? FileSize { get; set; }

    public string ExternalUrl { get; set; }

    public string Content { get; set; }

    public TextFormat? Format { get; set; }
}
