// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using saasLMS.AssessmentService.QuizAttempts;
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace saasLMS.AssessmentService.QuizAttempts;

public class QuizAttemptDto
{
    public Guid Id { get; set; }

    public Guid QuizId { get; set; }

    public Guid StudentId { get; set; }

    public int AttemptNumber { get; set; }

    public QuizAttemptStatus Status { get; set; }

    public DateTime StartedAt { get; set; }

    public DateTime? CompletedAt { get; set; }

    public Decimal Score { get; set; }

    public string SubmittedAnswersJson { get; set; }
}
