// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using saasLMS.AssessmentService.QuizAttempts;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;

// ReSharper disable once CheckNamespace
namespace saasLMS.AssessmentService.QuizAttempts;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IQuizAttemptAppService), typeof(QuizAttemptClientProxy))]
public partial class QuizAttemptClientProxy : ClientProxyBase<IQuizAttemptAppService>, IQuizAttemptAppService
{
    /// <summary>
    /// Returns all quiz attempts for a given quiz (instructor view).
    /// Mapped to: GET /api/assessment/quiz-attempts/{quizId}/results
    /// </summary>
    public virtual async Task<List<QuizAttemptDto>> GetListByQuizAsync(Guid quizId)
    {
        return await RequestAsync<List<QuizAttemptDto>>(nameof(GetListByQuizAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), quizId }
        });
    }

    /// <summary>
    /// Route auto-generated by ABP ConventionalControllers.
    /// POST /api/assessment/quiz-attempts/start
    /// </summary>
    public virtual async Task<QuizAttemptDto> StartAsync(StartQuizAttemptDto input)
    {
        return await RequestAsync<QuizAttemptDto>(nameof(StartAsync), new ClientProxyRequestTypeValue
        {
            { typeof(StartQuizAttemptDto), input }
        });
    }

    /// <summary>
    /// Mapped to: POST /api/assessment/quiz-attempts/{quizId}/submit
    /// </summary>
    public virtual async Task<QuizAttemptDto> SubmitAsync(Guid quizId, SubmitQuizAttemptDto input)
    {
        return await RequestAsync<QuizAttemptDto>(nameof(SubmitAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), quizId },
            { typeof(SubmitQuizAttemptDto), input }
        });
    }

    /// <summary>
    /// GetAsync is not currently exposed as an HTTP endpoint.
    /// </summary>
    public Task<QuizAttemptDto> GetAsync(Guid id)
    {
        throw new NotImplementedException("GetAsync is not exposed via HTTP endpoint.");
    }

    /// <summary>
    /// Route auto-generated by ABP ConventionalControllers.
    /// GET /api/assessment/quiz-attempts/my-attempt-by-quiz (quizId as query or route param)
    /// </summary>
    public virtual async Task<QuizAttemptDto?> GetMyAttemptByQuizAsync(Guid quizId)
    {
        return await RequestAsync<QuizAttemptDto?>(nameof(GetMyAttemptByQuizAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), quizId }
        });
    }

    /// <summary>
    /// HandleTimeoutAsync is not exposed via this proxy.
    /// </summary>
    public Task<QuizAttemptDto> HandleTimeoutAsync(Guid quizId)
    {
        throw new NotImplementedException("HandleTimeoutAsync is not exposed via this proxy.");
    }
}
