// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using saasLMS.AssessmentService.QuizAttempts;
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace saasLMS.AssessmentService.QuizAttempts;

public class QuizAttemptAnswerDto
{
    public Guid QuestionId { get; set; }

    public Guid? ChoiceId { get; set; }

    public string Value { get; set; }
}
