// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using saasLMS.AssessmentService.QuizAttempts;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;

// ReSharper disable once CheckNamespace
namespace saasLMS.AssessmentService.QuizAttempts;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IQuizAttemptAppService), typeof(QuizAttemptClientProxy))]
public partial class QuizAttemptClientProxy : ClientProxyBase<IQuizAttemptAppService>, IQuizAttemptAppService
{
    /// <summary>
    /// Returns all quiz attempts for a given quiz (instructor view).
    /// Mapped to: GET /api/assessment/quiz-attempts/{quizId}/results
    /// </summary>
    public virtual async Task<List<QuizAttemptDto>> GetListByQuizAsync(Guid quizId)
    {
        return await RequestAsync<List<QuizAttemptDto>>(nameof(GetListByQuizAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), quizId }
        });
    }

    /// <summary>
    /// StartAsync is handled by the student quiz flow controller.
    /// Not available via this proxy.
    /// </summary>
    public Task<QuizAttemptDto> StartAsync(StartQuizAttemptDto input)
    {
        throw new NotImplementedException(
            "StartAsync is not exposed through the instructor proxy. Use the student quiz flow.");
    }

    /// <summary>
    /// SubmitAsync is handled by QuizAttemptSubmitController.
    /// Not available via this proxy.
    /// </summary>
    public Task<QuizAttemptDto> SubmitAsync(Guid quizId, SubmitQuizAttemptDto input)
    {
        throw new NotImplementedException(
            "SubmitAsync is handled by QuizAttemptSubmitController. Use direct HTTP call.");
    }

    /// <summary>
    /// GetAsync is not currently exposed as an HTTP endpoint.
    /// </summary>
    public Task<QuizAttemptDto> GetAsync(Guid id)
    {
        throw new NotImplementedException("GetAsync is not exposed via HTTP endpoint.");
    }

    /// <summary>
    /// GetMyAttemptByQuizAsync is not exposed via this proxy.
    /// </summary>
    public Task<QuizAttemptDto?> GetMyAttemptByQuizAsync(Guid quizId)
    {
        throw new NotImplementedException("GetMyAttemptByQuizAsync is not exposed via this proxy.");
    }

    /// <summary>
    /// HandleTimeoutAsync is not exposed via this proxy.
    /// </summary>
    public Task<QuizAttemptDto> HandleTimeoutAsync(Guid quizId)
    {
        throw new NotImplementedException("HandleTimeoutAsync is not exposed via this proxy.");
    }
}
