// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using saasLMS.AssessmentService.QuizAttempts;
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace saasLMS.AssessmentService.QuizAttempts;

public class SubmitQuizAttemptDto
{
    public Guid? FormResponseId { get; set; }

    public QuizAttemptAnswerDto[] Answers { get; set; }

    public string SubmittedAnswersJson { get; set; }
}
