// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using saasLMS.ReportingService.Reports.Dtos.Outputs;
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace saasLMS.ReportingService.Reports.Dtos.Outputs;

public class CourseOutcomeReportViewDto
{
    public Guid TenantId { get; set; }

    public Guid CourseId { get; set; }

    public int AssignmentGradedCount { get; set; }

    public Decimal AssignmentScoreSum { get; set; }

    public Decimal AvgAssignmentScore { get; set; }

    public int QuizCompletedCount { get; set; }

    public Decimal QuizScoreSum { get; set; }

    public Decimal AvgQuizScore { get; set; }

    public int FinalScoreCount { get; set; }

    public Decimal FinalScoreSum { get; set; }

    public Decimal FinalScoreAvg { get; set; }

    public Decimal CompletionRate { get; set; }

    public Decimal PassRate { get; set; }

    public string ScoreDistributionJson { get; set; }

    public DateTime LastUpdatedAt { get; set; }
}
