// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using saasLMS.ReportingService.Reports.Dtos.Outputs;
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace saasLMS.ReportingService.Reports.Dtos.Outputs;

public class StudentCourseProgressViewDto
{
    public Guid TenantId { get; set; }

    public Guid CourseId { get; set; }

    public Guid StudentId { get; set; }

    public int CompletedLessonsCount { get; set; }

    public int TotalLessonsCount { get; set; }

    public Decimal LessonCompletionPercent { get; set; }

    public int AssignmentGradedCount { get; set; }

    public int TotalAssignmentsCount { get; set; }

    public Decimal AssignmentScoreSum { get; set; }

    public Decimal AssignmentCompletionPercent { get; set; }

    public Decimal AvgAssignmentScore { get; set; }

    public int QuizCompletedCount { get; set; }

    public int TotalQuizzesCount { get; set; }

    public Decimal QuizScoreSum { get; set; }

    public Decimal QuizCompletionPercent { get; set; }

    public Decimal AvgQuizScore { get; set; }

    public Decimal OverallProgress { get; set; }

    public Guid? LastAccessedLessonId { get; set; }

    public DateTime? LastAccessedAt { get; set; }

    public DateTime LastUpdatedAt { get; set; }
}
