// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using saasLMS.ReportingService.Reports.Dtos.Outputs;
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace saasLMS.ReportingService.Reports.Dtos.Outputs;

public class TenantSummaryReportViewDto
{
    public Guid TenantId { get; set; }

    public int TotalStudents { get; set; }

    public int ActiveStudents { get; set; }

    public int TotalInstructors { get; set; }

    public int TotalCourses { get; set; }

    public int ActiveCourses { get; set; }

    public DateTime LastUpdatedAt { get; set; }
}
