// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using saasLMS.EnrollmentService.Enrollments;
using saasLMS.EnrollmentService.Enrollments.Dtos.Inputs;
using saasLMS.EnrollmentService.Enrollments.Dtos.Outputs;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace saasLMS.EnrollmentService;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IEnrollmentAppService), typeof(EnrollmentClientProxy))]
public partial class EnrollmentClientProxy : ClientProxyBase<IEnrollmentAppService>, IEnrollmentAppService
{
    public virtual async Task<EnrollmentDto> EnrollAsync(EnrollCourseInput input)
    {
        return await RequestAsync<EnrollmentDto>(nameof(EnrollAsync), new ClientProxyRequestTypeValue
        {
            { typeof(EnrollCourseInput), input }
        });
    }

    public virtual async Task<EnrollmentDto> CancelAsync(CancelEnrollmentInput input)
    {
        return await RequestAsync<EnrollmentDto>(nameof(CancelAsync), new ClientProxyRequestTypeValue
        {
            { typeof(CancelEnrollmentInput), input }
        });
    }

    public virtual async Task<EnrollmentDto> GetByIdAsync(Guid id)
    {
        return await RequestAsync<EnrollmentDto>(nameof(GetByIdAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<EnrollmentDto> FindByCourseAsync(Guid courseId)
    {
        return await RequestAsync<EnrollmentDto>(nameof(FindByCourseAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), courseId }
        });
    }

    public virtual async Task<List<EnrollmentListItemDto>> GetMyEnrollmentsAsync(GetMyEnrollmentsInput input)
    {
        return await RequestAsync<List<EnrollmentListItemDto>>(nameof(GetMyEnrollmentsAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GetMyEnrollmentsInput), input }
        });
    }

    public virtual async Task<List<EnrollmentListItemDto>> GetEnrollmentsByCourseAsync(Guid courseId)
    {
        return await RequestAsync<List<EnrollmentListItemDto>>(nameof(GetEnrollmentsByCourseAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), courseId }
        });
    }

    public virtual async Task<ActiveEnrollmentDto> CheckActiveEnrollmentAsync(Guid courseId, Guid studentId)
    {
        return await RequestAsync<ActiveEnrollmentDto>(nameof(CheckActiveEnrollmentAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), courseId },
            { typeof(Guid), studentId }
        });
    }
}
