// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using saasLMS.EnrollmentService.Enrollments;
using saasLMS.EnrollmentService.Enrollments.Dtos.Inputs;
using saasLMS.EnrollmentService.Enrollments.Dtos.Outputs;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;

// ReSharper disable once CheckNamespace
namespace saasLMS.EnrollmentService;

public interface IEnrollmentAppService : IApplicationService
{
    Task<EnrollmentDto> EnrollAsync(EnrollCourseInput input);

    Task<EnrollmentDto> CancelAsync(CancelEnrollmentInput input);

    Task<EnrollmentDto> GetByIdAsync(Guid id);

    Task<EnrollmentDto> FindByCourseAsync(Guid courseId);

    Task<List<EnrollmentListItemDto>> GetMyEnrollmentsAsync(GetMyEnrollmentsInput input);

    Task<List<EnrollmentListItemDto>> GetEnrollmentsByCourseAsync(Guid courseId);

    Task<ActiveEnrollmentDto> CheckActiveEnrollmentAsync(Guid courseId, Guid studentId);
}
