// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using saasLMS.CourseCatalogService.Courses;
using saasLMS.CourseCatalogService.Lessons.Dtos.Outputs;
using saasLMS.CourseCatalogService.Materials.Dtos.Outputs;
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace saasLMS.CourseCatalogService.Lessons.Dtos.Outputs;

public class LessonInChapterDto
{
    public Guid Id { get; set; }

    public Guid ChapterId { get; set; }

    public string Title { get; set; }

    public int SortOrder { get; set; }

    public LessonContentState ContentState { get; set; }

    public MaterialInLessonDto[] Materials { get; set; }
}
