// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using saasLMS.CourseCatalogService.Materials.Dtos.Inputs;
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace saasLMS.CourseCatalogService.Materials.Dtos.Inputs;

public class CreateVideoLinkMaterialInput
{
    public Guid CourseId { get; set; }

    public Guid ChapterId { get; set; }

    public Guid LessonId { get; set; }

    public string Title { get; set; }

    public string ExternalUrl { get; set; }
}
