// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using saasLMS.CourseCatalogService.Materials.Dtos.Inputs;
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace saasLMS.CourseCatalogService.Materials.Dtos.Inputs;

public class UpdateFileMaterialInput
{
    public Guid CourseId { get; set; }

    public Guid ChapterId { get; set; }

    public Guid LessonId { get; set; }

    public Guid MaterialId { get; set; }

    public string StorageKey { get; set; }

    public string FileName { get; set; }

    public string MimeType { get; set; }

    public long? FileSize { get; set; }
}
