// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using saasLMS.NotificationService.Notifications;
using saasLMS.NotificationService.Notifications.Dtos.Inputs;
using saasLMS.NotificationService.Notifications.Dtos.Outputs;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace saasLMS.NotificationService.Notifications;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(INotificationAppService), typeof(NotificationClientProxy))]
public partial class NotificationClientProxy : ClientProxyBase<INotificationAppService>, INotificationAppService
{
    public virtual async Task<NotificationSummaryDto> GetMyNotificationsAsync()
    {
        return await RequestAsync<NotificationSummaryDto>(nameof(GetMyNotificationsAsync));
    }

    public virtual async Task<int> GetUnreadCountAsync()
    {
        return await RequestAsync<int>(nameof(GetUnreadCountAsync));
    }

    public virtual async Task MarkAsReadAsync(Guid notificationId)
    {
        await RequestAsync(nameof(MarkAsReadAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), notificationId }
        });
    }

    public virtual async Task MarkAllAsReadAsync()
    {
        await RequestAsync(nameof(MarkAllAsReadAsync));
    }

    public virtual Task SendNotificationAsync(SendNotificationInput input)
    {
        throw new NotImplementedException("SendNotificationAsync is a server-to-server integration method and is not available via the client proxy.");
    }
}
