// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using saasLMS.EnrollmentService.Enrollments.Dtos.Outputs;
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace saasLMS.EnrollmentService.Enrollments.Dtos.Outputs;

public class ActiveEnrollmentDto
{
    public bool IsActive { get; set; }

    public Guid? EnrollmentId { get; set; }

    public DateTime? EnrolledAt { get; set; }
}
