// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using saasLMS.EnrollmentService.Enrollments;
using saasLMS.EnrollmentService.Enrollments.Dtos.Outputs;
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace saasLMS.EnrollmentService.Enrollments.Dtos.Outputs;

public class EnrollmentDto
{
    public Guid Id { get; set; }

    public Guid CourseId { get; set; }

    public Guid StudentId { get; set; }

    public EnrollmentStatus Status { get; set; }

    public DateTime EnrolledAt { get; set; }

    public DateTime? CompletedAt { get; set; }

    public DateTime? CancelledAt { get; set; }
}
