config:
  selfUrl: # https://blazor-webapp.saaslms.dev
  gatewayUrl: # http://saaslms-st-gateway-web
  authServer:
    authority: # http://saaslms-st-authserver
    requireHttpsMetadata: # "false"
    isOnK8s: # "true"
    metaAddress: # http://saaslms-st-authserver
  dotnetEnv: # 
  redisHost: #
  rabbitmqHost: #
  elasticsearchUrl: #
  stringEncryptionDefaultPassPhrase: gsKnGZ041HLL4IM8
  AbpLicenseCode: #

ingress:
  host: # blazor-webapp.saaslms.dev
  tlsSecret: saaslms-tls

image:
  repository: mycompanyname/saaslms-app-blazor-webapp
  tag: latest
  pullPolicy: IfNotPresent

env: {}   